version: "3"
services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: http-egress
      EGRESS_WEBHOOK_URL: https://hookb.in/b99XkkOQz1uKGq00GBgg
      HANDLER_PORT: 80
      METHOD: GET
      LABELS: "temp"
    ports:
      - 5000:80
