version: "3"
services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: webhook
      EGRESS_WEBHOOK_URL: https://hookb.in/r1YwjDyn7BHzWWJVK8Gq
      HANDLER_PORT: 80
    ports:
      - 5000:80
